maven-build:
  stage: build
  
 
  script:
    - mvn --version
    - mvn clean install -Dmaven.test.skip=true
    - whoami
    - cd ~
    - ls -la
  artifacts:
    paths:
      - $JAR_FILE
  except:
     - tags
  
  tags:
     - linux
